  
$engine: 2
$minFxVersion: 3362
name: Zombie
version: v1.0.0
author: Hamy-os
description: This is a zombie rpg framework built for fivem
    
tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 88f4f974b855e0bf2ca5f51b9916648bd5b7d44b
    subpath: resources
    dest: ./resources
  
    # Download zombie
  - action: download_github
    src: https://github.com/Dislaik/zombieoutbreak
    dest: ./resources/zombieoutbreak

  # Download and prepare server.cfg  / database
  - action: download_github
    src: https://github.com/tabarra/txAdmin-recipes/
    dest: ./tmp/zombie

  - action: download_github
    src: https://github.com/brouznouf/fivem-mysql-async
    dest: ./resources/mysql-async

  - action: move_path
    src: ./tmp/zombie/zombie/server.cfg
    dest: ./server.cfg
    
  - action: move_path
    src: ./tmp/zombie/zombie/logo.png
    dest: ./logo.png

  - action: connect_database
    
  - action: query_database
    file: ./resources/zombie/zombieoutbreak.sql

  - action: remove_path
    path: ./tmp
