$engine: 2
name: vRP
version: v1.0.1
author: DunkoUK and Hamy
description: vRP is a roleplaying framework made for fivem.

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 88f4f974b855e0bf2ca5f51b9916648bd5b7d44b
    subpath: resources
    dest: ./resources
  
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/Hamy-os/txAdmin-recipes/
    dest: ./tmp/vRP

  - action: download_github
    src: https://github.com/Hamy-os/sql-recipe
    dest: ./tmp/sql

  - action: download_github
    src: https://github.com/Blumlaut/EasyAdmin
    ref: 71b9f1340f6840abe6748dee40c472e60f38fb03
    dest: ./resources/EasyAdmin

  - action: move_path
    src: ./tmp/vRP/vRP/server.cfg
    dest: ./server.cfg

  # Download basic vRP things
  - action: download_github
    src: https://github.com/Hamy-os/dunko_vrp
    ref: master
    dest: ./resources/[vRP]

  ## KL HUD v2
  - action: download_github
    src: https://github.com/Kilichi/Kl_HudV2
    ref: ac8a321ff335706509bdc6122a2984a80082e669
    dest: ./resources/Kl_HudV2

  - action: connect_database

  - action: query_database
    file: ./tmp/sql/vrp_business.sql

  - action: query_database
    file: ./tmp/sql/vrp_characters.sql

  - action: query_database
    file: ./tmp/sql/vrp_coins.sql

  - action: query_database
    file: ./tmp/sql/vrp_garages.sql

  - action: replace_string
    mode: all_vars
    file: ./resources/[vRP]/ghmattimysql/config.json

  - action: replace_string
    mode: all_vars
    file: ./server.cfg

  - action: remove_path
    path: ./tmp
